// <auto-generated />
using BrandX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrandX.Migrations
{
    [DbContext(typeof(InfoData))]
    partial class InfoDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BrandX.Models.FinalsData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Assignment1");

                    b.Property<int>("Assignment2");

                    b.Property<int>("Assignment3");

                    b.Property<int>("Exam");

                    b.Property<string>("Name");

                    b.Property<int>("Quiz1");

                    b.Property<int>("Quiz2");

                    b.Property<int>("Quiz3");

                    b.HasKey("ID");

                    b.ToTable("Finals");
                });

            modelBuilder.Entity("BrandX.Models.MidtermData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Assignment1");

                    b.Property<int>("Assignment2");

                    b.Property<int>("Assignment3");

                    b.Property<int>("Exam");

                    b.Property<string>("Name");

                    b.Property<int>("Quiz1");

                    b.Property<int>("Quiz2");

                    b.Property<int>("Quiz3");

                    b.HasKey("ID");

                    b.ToTable("Midterm");
                });

            modelBuilder.Entity("BrandX.Models.PrefinalData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Assignment1");

                    b.Property<int>("Assignment2");

                    b.Property<int>("Assignment3");

                    b.Property<int>("Exam");

                    b.Property<string>("Name");

                    b.Property<int>("Quiz1");

                    b.Property<int>("Quiz2");

                    b.Property<int>("Quiz3");

                    b.HasKey("ID");

                    b.ToTable("Prefinal");
                });

            modelBuilder.Entity("BrandX.Models.PrelimData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Assignment1");

                    b.Property<int>("Assignment2");

                    b.Property<int>("Assignment3");

                    b.Property<int>("Exam");

                    b.Property<string>("Name");

                    b.Property<int>("Quiz1");

                    b.Property<int>("Quiz2");

                    b.Property<int>("Quiz3");

                    b.HasKey("ID");

                    b.ToTable("Prelim");
                });

            modelBuilder.Entity("BrandX.Models.StudentInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("ContactNo");

                    b.Property<string>("Course");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("StudentInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
